### ISSUE TITLE
On the problem of not being able to decompose "nonconvex shapes" into associations of "convex shapes"

### ISSUE THREAD

**Issue by miyukin73** [kevinzakka/obj2mjcf#10]
Hello,
I'd like to simulate pouring objects into a cup.
So, I created the STL file of the cup in CAD.

However, since the cup stl file is a non-convex geometry, it must be broken down into convex geom unions and they must all be attached to the same body in order to simulate in Mujoco.

So I was taught [here](https://github.com/deepmind/mujoco/discussions/357#discussioncomment-3012322) before how to convert from stl files to obj files.

It worked that time, but when I tried again, when I ran the code A, only one file was generated and it was still a non-convex geometry.

What is the problem?
I would like to know ....
Thank you in advance.
[Cup (2).zip](https://github.com/kevinzakka/obj2mjcf/files/9532825/Cup.2.zip)

**Comment by kevinzakka** [comment]
Hi @miyukin73,

You need to set `--vhacd-args.enable` when processing this mesh. You'll probably want to tweak the parameters of V-HACD though since it might not generate a good approximation with the default args.
