### ISSUE TITLE
Additional question #10 concerning the change to a concave model

### ISSUE THREAD

**Issue by miyukin73** [kevinzakka/obj2mjcf#13]
Hi, @kevinzakka 

I am very sorry for repeatedly pestering you.

However, I would like to ask an additional new question regarding #10 , as I did not understand your previous answer regarding the change to a concave model and it was closed.

You told me that I should probably want to tweak the parameters of V-HACD though since it might not generate a good approximation with the default args., 
but how exactly can the values be changed?

--------------------------------------------------------------
I would like to reiterate the situation just to be sure.

I would like to use Mujoco to simulate a ball in a cup and pour it.
So I have created an STL file of the cup and read it in as an xml file and have it output.

However, I found the following text at the URL site below.

" if you want to model a non-convex shape, you have to decompose it into a union of convex geoms and attach all of them to the same body. "
https://mujoco.readthedocs.io/en/latest/overview.html

In fact, using the STL file of the created cup (black object), the object (green sphere) did not fit into the cup as shown in the attached photo.
![image](https://user-images.githubusercontent.com/63595993/175294879-40f1fec7-f51e-425b-8258-13614fa96289.png)

Regarding the above problem, I was taught how to decompose a non-convex shape model into a convex shape model [here](https://github.com/deepmind/mujoco/discussions/357#discussioncomment-3011107).
As a result, I was able to correctly decompose the model at the time you taught me and generated about 20~30 obj files named "XX_collision_YY" in the newly generated folder ("Cup0722v1"), as shown in the image below.

[Cup0722v1.zip](https://github.com/kevinzakka/obj2mjcf/files/9650411/Cup0722v1.zip)

![image](https://user-images.githubusercontent.com/63595993/192402572-0f0bfa98-857d-437d-a316-2ea740b53e5a.png)

However, when I run it now, the collision obj file is not generated and only the original obj file and xml file exist in the newly generated folder ("Cup0722v1").

[Cup0722v1_fail.zip](https://github.com/kevinzakka/obj2mjcf/files/9650425/Cup0722v1_fail.zip)

![image](https://user-images.githubusercontent.com/63595993/192403168-8726afcd-d7d5-486c-8770-914af14a04ca.png)

I have written this at length, but to summarize the current problem, 
I am having trouble with the nonconvex shape model not being properly decomposed when I run thebelow program.

`obj2mjcf --obj-dir . --obj-filter cup --save-mjcf --compile-model --vhacd-args.enable`

I am truly sorry for the many times I have bothered you in your busy schedule, but I would appreciate your advice.

Thank you in advance.

**Comment by kevinzakka** [comment]
Hi @miyukin73, sorry for the delayed response. Were you able to make progress on this?

**Comment by miyukin73** [comment]
Hello @kevinzakka,  thank you for your reply.

No, the issue of the concave model not breaking down into multiple convex models remains unresolved.

I would be very grateful if you could check. Thank you very much.

**Comment by kevinzakka** [comment]
I downloaded your OBJ file and ran:

```bash
obj2mjcf --obj-dir . --save-mjcf --compile-model --verbose --vhacd-args.enable
```

and it worked fine. Here's the generated result, which you can load into the simulate app.

[Cup0722v1.zip](https://github.com/kevinzakka/obj2mjcf/files/9795475/Cup0722v1.zip)

**Comment by miyukin73** [comment]
Thank you so much for taking your time to run it and confirm it...!!


[stl_file.zip](https://github.com/kevinzakka/obj2mjcf/files/9807528/stl_file.zip)

I tried again with cup_thick.obj above but only one file was generated.
[cup_thick.zip](https://github.com/kevinzakka/obj2mjcf/files/9807561/cup_thick.zip)

![image](https://user-images.githubusercontent.com/63595993/196365672-1c791a9a-c074-4dd0-a569-debb6ea56ad1.png)

Is there any possible problem?

I would appreciate it if you could check.

**Comment by kevinzakka** [comment]
Did you install V-HACD by running the script mentioned in the [readme](https://github.com/kevinzakka/obj2mjcf#extra-v-hacd-40)? Can you show me your terminal output when you set `--verbose` on? If it can't find V-HACD, then it skips the step.

**Comment by miyukin73** [comment]
Hi, @kevinzakka 

Thank you for the reply.

I installed V-HACD, but when I setteed --verbose, "Command not found" is outputted as below.

![image](https://user-images.githubusercontent.com/63595993/196608403-09fb6fd6-d0c2-490e-82d7-0462c03ff480.png)
