### ISSUE TITLE
Add Transparency 

### ISSUE THREAD

**Issue by AlexanderKhazatsky** [kevinzakka/obj2mjcf#2]
Hello, thanks so much for making this! Could you update the code to also take into consideration the texture / color transparency (aka alpha value).

I think the change should be somewhere around here. Ilya has successfully done this as well in case you get stuck :)

https://github.com/kevinzakka/obj2mjcf/blob/d1073fa32d9e86687d31dfe0972fd72ac2c02ae2/obj2mjcf/_cli.py#L304

**Comment by kevinzakka** [comment]
Hey @AlexanderKhazatsky, can you try out PR #3 and let me know how it works?

**Comment by AlexanderKhazatsky** [comment]
Thank you so much Kevin!!
