### ISSUE TITLE
unknown mesh file type 1_0.obj 

### ISSUE THREAD

**Issue by Sam-WangXZ** [kevinzakka/obj2mjcf#22]
unknown mesh file type 1_0.obj 
after  obj2mjcf --obj-dir /path/to/your/obj/files --save-mjcf --compile-model --verbose  i use mujoco to open xml file but out put is unknown mesh file type 1_0.obj 
![image](https://github.com/kevinzakka/obj2mjcf/assets/116878306/5f9dffaf-7654-4044-b4bc-dbea7ae70ef6)

**Comment by kevinzakka** [comment]
Hey @Sam-WangXZm, you're using MuJoCo 2.10 but the minimum requirement to use OBJs is 2.1.2.

**Comment by Sam-WangXZ** [comment]
thanks a lot , i just noticed this thing , sorry
