### ISSUE TITLE
collision_model assembly test

### ISSUE THREAD

**Issue by turbohiro** [kevinzakka/obj2mjcf#6]
Hi Kevin, you did a great job! I have a question when I try to do the peg-in-hole experiment. I firstly use your code to transform the peg and hole object into the collision models separately (circle.xml and peg_circle.xml). Then I try to let the peg fall into the hole, but it always fails(assembly.xml). I am not familiar with mujoco, can you help me explain the reason?
[assembly_test.zip](https://github.com/kevinzakka/obj2mjcf/files/9064637/assembly_test.zip)

**Comment by kevinzakka** [comment]
Hi @turbohiro, cool models! Open assembly.xml in `simulate`, press 2 to hide the visual geoms, then press 3 to display the collision geoms. You'll see why it's not falling inside the hole.

Unsure why the geoms got flipped, did you use any other tool?

**Comment by turbohiro** [comment]
Yes, after I add the quat value to the collision model. It works well! Thank you, Kevin!
