### ISSUE TITLE
Where is the output files?

### ISSUE THREAD

**Issue by HeegerGao** [kevinzakka/obj2mjcf#7]
Hi, I am using your code by running a python file that contains:
```
import pathlib
import subprocess

# Path to the directory containing this file.
_THIS_DIR = pathlib.Path(__file__).parent.absolute()


def test_runs_without_error() -> None:
    retcode = subprocess.call(
        [
            "obj2mjcf",
            "--obj-dir",
            "./test,
            "--save-mtl",
            "--save-mjcf",
            "--compile-model",
            "--verbose",
        ]
    )
    assert retcode == 0
```
When I ran it, I didn't get anything output in the terminal nor in the folder. Does this represent a successful or unsuccessful run? If it is successful, where are the output files? Thank you!

**Comment by kevinzakka** [comment]
It's in the same directory as the obj file. It's a directory with the same name as the obj file. The code isn't too big, you can verify this [here](https://github.com/kevinzakka/obj2mjcf/blob/main/obj2mjcf/_cli.py#L248).

**Comment by HeegerGao** [comment]
Thanks for your prompt reply. I think maybe I have made something wrong because I didn't get the .XML file in the same directory, nor any info output in the terminal. Will an unsuccessful run output something in the terminal?

**Comment by kevinzakka** [comment]
Run the command in a terminal just to check and remember to set verbose flag on. LMK if that helps.

**Comment by HeegerGao** [comment]
Oh, I think I find the problem, my stupid mistake. I name the python file `obj2mjcf.py`, which is the same name as the package. Then the command file at `~/anaconda3/envs/{YOUR_ENV_NAME}/bin` will import this python file rather than the original package. Anyway, everything is alright now. Thank you.
