### ISSUE TITLE
Poor results on some objects

### ISSUE THREAD

**Issue by HeegerGao** [kevinzakka/obj2mjcf#8]
Hi, I am using your codes to convert some .obj files to the mujoco simulator. However, I find results from using the V-HACD method as an approximation are very poor for some objects. 

For example, I am using [HOPE Dataset](https://github.com/swtyree/hope-dataset), and for one of the object [AlphabetSoup](https://cloud.tsinghua.edu.cn/d/0305450bc7864413a069/), the [results](https://cloud.tsinghua.edu.cn/d/0305450bc7864413a069/) are very poor even when I set `vhacd-args.max-output-convex-hulls=30`:

![image](https://user-images.githubusercontent.com/48041218/179362598-af0215b5-ac68-4a90-8330-43a2bc2c9cd7.png)

Do you have any suggestions for these objects? Thank you!

**Comment by kevinzakka** [comment]
This [video](https://www.youtube.com/watch?v=Sa1NE-St8iA) might be helpful.
